In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
tf.random.set_seed(42)

In [ ]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [ ]:
x_data = np.array([[h]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.]]], dtype=float32)

In [ ]:
x_data.shape # (sample의 갯수, token의 갯수,  token의 embedding의 수) => (1, 1, 4)

(1, 1, 4)

In [ ]:
# input dimension : 4
# output dimension : 2 -> hidden_size로 세팅 -> 몇개의 클래스로 분류하는지에 따름

hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences = True, return_state= True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.31773362 -0.11744198]]] 	 shape : (1, 1, 2)
states : [[ 0.31773362 -0.11744198]] 	 shape : (1, 2)


In [ ]:
# return_state = False
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences = True, return_state= False)
output = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.54152584 -0.00444528]]] 	 shape : (1, 1, 2)


In [ ]:
# return_sequences = False -> 맨 마지막 것만 출력

hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences = False, return_state= True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[-0.12818007  0.04968958]] 	 shape : (1, 2)
states : [[-0.12818007  0.04968958]] 	 shape : (1, 2)


In [ ]:
# simpler method
rnn = layers.SimpleRNN(units = hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.14876226 -0.53846276]]] 	 shape : (1, 1, 2)
states : [[ 0.14876226 -0.53846276]] 	 shape : (1, 2)


In [ ]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [ ]:
x_data.shape

(1, 5, 4)

In [ ]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] 	 shape : (1, 5, 4)
output : [[[-0.4290882   0.09134389]
  [-0.3537549  -0.66583985]
  [ 0.203766    0.7295689 ]
  [ 0.89181894  0.05618912]
  [ 0.92070085  0.3930762 ]]] 	 shape : (1, 5, 2)
states : [[0.92070085 0.3930762 ]] 	 shape : (1, 2)


In [ ]:
x_data = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)

In [ ]:
x_data.shape

(3, 5, 4)

In [ ]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states : {} \t shape : {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]] 	 shape : (3, 5, 4)
output : [[[ 0.05686769  0.34700885]
  [ 0.5258374  -0.33018067]
  [ 0.83039427 -0.7154057 ]
  [ 0.9328015  -0.72991735]
  [ 0.9380278   0.44018933]]

 [[ 0.6841841  -0.09805116]
  [ 0.785885    0.30606773]
  [ 0.67244357 -0.9004724 ]
  [ 0.9403924  -0.6000644 ]
  [ 0.9285215  -0.79493284]]

 [[ 0.549907   -0.57478976]
  [ 0.88622147 -0.65178597]
  [ 0.9542981  -0.42552215]
  [ 0.93915325 -0.5644942 ]
  [ 0.9242802  -0.8019193 ]]] 	 shape : (3, 5, 2)
states : [[ 0.9380278   0.44018933]
 [ 0.9285215  -0.79493284]
 [ 0.9242802  -0.8019193 ]] 	 shape : (3, 2)


In [ ]:
# vocab
idx2char = ['토', '마', '를', '먹', '자']

x_data = [[0, 0, 1, 2, 4, 3]] # 토 토 마 를 자 먹
y_data = [[0, 1, 0, 2, 3, 4]] # 토 마 토 를 먹 자

# idx2char 갯수
num_classes = 5

# 단어의 갯수 (문장에서 단어를 추출할 때는 보통 num_classes = input_dim)
input_dim = 5

# data의 갯수
sequence_len = 6

learning_rate = 0.1

x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

print(x_one_hot)
print(x_one_hot.shape)
print(y_one_hot)
print(y_one_hot.shape)

[[[1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]
(1, 6, 5)


In [ ]:
from tensorflow.keras.models import Model

model = tf.keras.Sequential()
cell = layers.SimpleRNNCell(units=num_classes, input_shape=(sequence_len, input_dim))


model.add(layers.RNN(cell=cell, return_sequences=True, return_state=False, input_shape= (sequence_len, input_dim)))
model.add(layers.TimeDistributed(layers.Dense(units=num_classes, activation='softmax')))

model.compile(loss='categorical_crossentropy', 
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
rnn_4 (RNN)                  (None, 6, 5)              55        
_________________________________________________________________
time_distributed (TimeDistri (None, 6, 5)              30        
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_one_hot, y_one_hot, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 12ms/step - loss: 0.7215 - accuracy: 0.6667
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 0.5529 - accuracy: 0.8333
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 0.3976 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 0.2771 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.1912 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 0.1357 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0998 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0748 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0564 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0428 - accuracy: 1.0000


In [ ]:
pred = model.predict(x_one_hot)
pred

array([[[9.7922623e-01, 1.8294841e-02, 1.4250401e-04, 2.1384400e-03,
         1.9798917e-04],
        [1.5331188e-02, 9.7470719e-01, 9.3477471e-03, 3.7228130e-04,
         2.4155516e-04],
        [9.2962706e-01, 6.2376283e-02, 5.8489712e-04, 7.3525417e-03,
         5.9293114e-05],
        [4.8675499e-04, 1.1402947e-02, 9.7685754e-01, 3.1021219e-03,
         8.1506474e-03],
        [8.9404816e-03, 6.7214697e-04, 2.7830189e-03, 9.6905959e-01,
         1.8544808e-02],
        [4.6794870e-04, 7.4812438e-04, 6.9569289e-03, 1.3092987e-02,
         9.7873402e-01]]], dtype=float32)

In [ ]:
for i, word in enumerate(pred):
    print([idx2char[c] for c in np.argmax(word, axis=1)])

['토', '마', '토', '를', '먹', '자']
